### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Izak8** [JC-Yoshi/CGMA-Level-Design-Course#1]
Crashes CONSTANTLY ugh PLS FIX JOSH

**Comment by JC-Yoshi** [comment]
fixes made, 
- local height map deleted, recreated
- project hierarchy rearranged 
- rebuilt lighting
- nanite disabled 
- lod loading fixing/culling fixes

**Comment by JC-Yoshi** [comment]
week 5 branch built with fixes made
